# Generated by Django 3.0.8 on 2020-07-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tfno',
            field=models.CharField(max_length=7, verbose_name='Phone'),
        ),
    ]
